In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv("diabetes_prediction_dataset.csv")

In [26]:
df.head(20)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
5,Female,20.0,0,0,never,27.32,6.6,85,0
6,Female,44.0,0,0,never,19.31,6.5,200,1
7,Female,79.0,0,0,No Info,23.86,5.7,85,0
8,Male,42.0,0,0,never,33.64,4.8,145,0
9,Female,32.0,0,0,never,27.32,5.0,100,0
10,Female,53.0,0,0,never,27.32,6.1,85,0
11,Female,54.0,0,0,former,54.70,6.0,100,0
12,Female,78.0,0,0,former,36.05,5.0,130,0
13,Female,67.0,0,0,never,25.69,5.8,200,0
14,Female,76.0,0,0,No Info,27.32,5.0,160,0
15,Male,78.0,0,0,No Info,27.32,6.6,126,0
16,Male,15.0,0,0,never,30.36,6.1,200,0
17,Female,42.0,0,0,never,24.48,5.7,158,0
18,Female,42.0,0,0,No Info,27.32,5.7,80,0
19,Male,37.0,0,0,ever,25.72,3.5,159,0

In [27]:
df.describe

<bound method NDFrame.describe of        gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19
1      Female  54.0             0              0         No Info  27.32
2        Male  28.0             0              0           never  27.32
3      Female  36.0             0              0         current  23.45
4        Male  76.0             1              1         current  20.14
...       ...   ...           ...            ...             ...    ...
99995  Female  80.0             0              0         No Info  27.32
99996  Female   2.0             0              0         No Info  17.37
99997    Male  66.0             0              0          former  27.83
99998  Female  24.0             0              0           never  35.42
99999  Female  57.0             0              0         current  22.43

       HbA1c_level  blood_glucose_level  diabetes
0              6.6                  140         0
1              6.6                   80         0
2              5.7                  158         0
3              5.0                  155         0
4              4.8                  155         0
...            ...                  ...       ...
99995          6.2                   90         0
99996          6.5                  100         0
99997          5.7                  155         0
99998          4.0                  100         0
99999          6.6                   90         0

[100000 rows x 9 columns]>

In [28]:
df.tail()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [29]:
df.shape

(100000, 9)

In [30]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [31]:
df.dtypes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [35]:
df.isnull()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,False,False,False

In [36]:
df.isnull().values.any()

np.False_

In [39]:
# Convert gender into numbers
gender_mapping = {
    "Male": 1,
    "Female": 2,
    "Other": 3
}

df["gender"] = df["gender"].map(gender_mapping)


# Convert smoking history into numbers
smoking_mapping = {
    "never": 1,
    "No Info": 2,
    "current": 3,
    "former": 4,
    "ever": 5,
    "not current": 6
}

df["smoking_history"] = df["smoking_history"].map(smoking_mapping)


# Display the updated dataset
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,NaN,80.0,0,1,NaN,25.19,6.6,140,0
1,NaN,54.0,0,0,NaN,27.32,6.6,80,0
2,NaN,28.0,0,0,NaN,27.32,5.7,158,0
3,NaN,36.0,0,0,NaN,23.45,5.0,155,0
4,NaN,76.0,1,1,NaN,20.14,4.8,155,0

In [40]:
# Find unique values in gender
print("Unique gender values:")
print(df["gender"].unique())

# Find unique values in smoking history
print("\nUnique smoking history values:")
print(df["smoking_history"].unique())

Unique gender values:
[nan]

Unique smoking history values:
[nan]

In [41]:
print(df.columns.tolist())

['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']